const Category = require('../models/Category');
const Project = require('../models/Project');
const mongoose = require('mongoose');

// Get all categories (including hidden ones for admin)
exports.getAll = async (req, res, next) => {
  try {
    const { includeHidden } = req.query;
    const filter = {};
    
    // If includeHidden is not 'true', only show visible categories
    if (includeHidden !== 'true') {
      filter.isHidden = false;
    }
    
    const categories = await Category.find(filter).sort({ order: 1, name: 1 });
    
    // Get project count for each category
    const categoriesWithCount = await Promise.all(
      categories.map(async (cat) => {
        const count = await Project.countDocuments({ category: cat.name });
        return { ...cat.toObject(), projectCount: count };
      })
    );
    
    res.json(categoriesWithCount);
  } catch (error) {
    next(error);
  }
};

// Get a single category by ID or slug
exports.getOne = async (req, res, next) => {
  try {
    const { id } = req.params;
    const query = mongoose.Types.ObjectId.isValid(id) 
      ? { _id: id } 
      : { slug: id };
    
    const category = await Category.findOne(query);
    if (!category) {
      return res.status(404).json({ message: 'Category not found' });
    }
    
    const projectCount = await Project.countDocuments({ category: category.name });
    res.json({ ...category.toObject(), projectCount });
  } catch (error) {
    next(error);
  }
};

// Create a new category - FIXED
exports.create = async (req, res, next) => {
  try {
    const { name, description, order } = req.body;
    
    if (!name || name.trim() === '') {
      return res.status(400).json({ message: 'Category name is required' });
    }
    
    // Check for duplicate name (case insensitive)
    const existing = await Category.findOne({ 
      name: { $regex: new RegExp(`^${name.trim()}$`, 'i') }
    });
    
    if (existing) {
      return res.status(400).json({ 
        message: `Category "${name}" already exists. Please use a different name.` 
      });
    }
    
    // Create category - slug will be auto-generated by pre-save middleware
    const category = new Category({
      name: name.trim(),
      description: description || '',
      order: order || 0,
      isHidden: false,
    });
    
    await category.save();
    
    res.status(201).json(category);
  } catch (error) {
    // Handle duplicate key error
    if (error.code === 11000) {
      return res.status(400).json({ 
        message: `Category with this name already exists. Please use a different name.` 
      });
    }
    next(error);
  }
};

// Update a category
exports.update = async (req, res, next) => {
  try {
    const { id } = req.params;
    const { name, description, order, isHidden } = req.body;
    
    const category = await Category.findById(id);
    if (!category) {
      return res.status(404).json({ message: 'Category not found' });
    }
    
    // If renaming, check for conflicts
    if (name && name !== category.name) {
      const existing = await Category.findOne({ 
        name: { $regex: new RegExp(`^${name.trim()}$`, 'i') },
        _id: { $ne: id }
      });
      
      if (existing) {
        return res.status(400).json({ 
          message: `Category "${name}" already exists. Please use a different name.` 
        });
      }
      
      // Update all projects with this category name
      await Project.updateMany(
        { category: category.name },
        { category: name.trim() }
      );
      
      category.name = name.trim();
      // Slug will be auto-generated on save
    }
    
    if (description !== undefined) category.description = description;
    if (order !== undefined) category.order = order;
    if (isHidden !== undefined) category.isHidden = isHidden;
    
    await category.save();
    
    const projectCount = await Project.countDocuments({ category: category.name });
    res.json({ ...category.toObject(), projectCount });
  } catch (error) {
    if (error.code === 11000) {
      return res.status(400).json({ 
        message: `Category with this name already exists. Please use a different name.` 
      });
    }
    next(error);
  }
};

// Permanently delete a category (only if no projects use it)
exports.remove = async (req, res, next) => {
  try {
    const { id } = req.params;
    
    const category = await Category.findById(id);
    if (!category) {
      return res.status(404).json({ message: 'Category not found' });
    }
    
    // Check if any projects use this category
    const projectCount = await Project.countDocuments({ category: category.name });
    if (projectCount > 0) {
      return res.status(400).json({ 
        message: `Cannot delete category "${category.name}" because it is used by ${projectCount} project(s). Please reassign or delete those projects first.`,
        projectCount
      });
    }
    
    await category.deleteOne();
    res.json({ 
      message: `Category "${category.name}" deleted successfully`,
      deleted: true
    });
  } catch (error) {
    next(error);
  }
};

// Toggle category visibility
exports.toggleVisibility = async (req, res, next) => {
  try {
    const { id } = req.params;
    const { isHidden } = req.body;
    
    const category = await Category.findById(id);
    if (!category) {
      return res.status(404).json({ message: 'Category not found' });
    }
    
    category.isHidden = isHidden !== undefined ? isHidden : !category.isHidden;
    await category.save();
    
    res.json({
      message: `Category "${category.name}" ${category.isHidden ? 'hidden' : 'visible'}`,
      category
    });
  } catch (error) {
    next(error);
  }
};